sudo: required

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_db_test;' -U postgres

deploy:
  provider: heroku
  api_key:
    secure: "7628ec78-8acb-4a65-a7b3-620b0b4c0c92"